name: csvlint
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    name: CSV構文チェック
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Prepare csvlint
      run: go get github.com/Clever/csvlint/cmd/csvlint
    - name: Run csvlint
      run: csvlint words.csv
